### ISSUE TITLE
Terminate account

### ISSUE THREAD

**Issue by yddgd** [bytemedrive/android#45]
In menu (or under profile, TBD), add a possibility (item/button) to terminate the account. 

After selecting, the user is asked to confirm by typing their password. 

After 24 hours, the account and all related data is deleted.

**Comment by tonda100** [comment]
Delete app files endpoint:
DELETE `/wallets/{walletId}/files`
```
"ids": []
```

**Comment by tonda100** [comment]
Delete customer endpoint:
DELETE `/customers/{usernameSha3}`
Header: `Authorization: Hash sha3-256(tonda100:Password1.) => Authorization: Hash 69604c6f2696d3545eb00b6aa8080657f2a7dc74ffcd59c66e49ba66b2341bea`
