### ISSUE TITLE
Changed app orientation when adding credit by credit card

### ISSUE THREAD

**Issue by horavamartin** [bytemedrive/android#76]
1. App orientation is changed when I clicked at pay by credit card.
2. Payment is not possible to finish. The button is disabled.
![IMG_4594](https://github.com/bytemedrive/android/assets/2638409/1f217950-2fd9-4b8d-a290-d1a3e1f25a01)

**Comment by k3nda** [comment]
Cannot reproduce on mobile devices. 
Tried to find out what is possible to do but found nothing. We have latest version of Stripe library and card dialog is their component and cannot do anything with it, just change colors. I worked on it about an hour without result.
